### ISSUE TITLE
WishList

### ISSUE THREAD

**Issue by threezool** [SavelyAB/Savely-Api#5]
A child user has a wishlist that it can add items to that it wants as a gift. It should be able to add/remove items and parents can set savings goals on specific items.

### Backend / API

- [ ] Present a child user with its wishlist when requested by the API
- [ ] Present a parent user with all the connected children wishlists grouped by users
- [ ] Present a child user with all shared wishlists from other child users grouped by users
- [ ] Support adding a new item
- [ ] Support removing a item
- [ ] Support editing the item

### Dependencies

- [ ] Database models
