### ISSUE TITLE
User Connections

### ISSUE THREAD

**Issue by threezool** [SavelyAB/Savely-Api#6]
Users need to be able to add other users, for now we need that a child can add a parent and vice versa but in the long term a child user could add another child user like friends or class mates.

### Backend / API

- [ ] Endpoint for connecting a parent to a child
- [ ] Endpoint for connecting a child to a parent
- [ ] Endpoint for connecting a child to a child
- [ ] Endpoint for removing connection
- [ ] Endpoint for displaying all connections grouped by type based on user (child -> child, child -> parent etc)

### Dependencies

- [ ] Database Models

### Requirements

- A distinction has to be built in between the different connection types
- A parent can only add a child, not other parents
- A child can add both a parent and a child
