### ISSUE TITLE
User Types

### ISSUE THREAD

**Issue by threezool** [SavelyAB/Savely-Api#7]
There are two types of users in the system, a child user and a parent (adult) user.

### Backend / API

- [ ] When a user registers it needs to be marked if it is a child or parent user (DoB?)
- [ ] A parent user can see all connected child users wishlists
- [ ] A child user can only see its own wishlist
- [ ] A child user can see shared wishlists from other child users

### Dependencies

- [ ] Database Models

### Requirements

- The user information needs to comply with the new GDPR directive from EU
